#templatefile -v "1.0" -n "Piecemaker" -d "Generated by a free Picasa template from www.paulvanroekel.nl; Piecemaker was created by www.modularweb.net"

define imageWidth 800
define imageHeight 800

define shadowedThumbnails 0
define thumbnailWidth 10
define thumbnailHeight 10

include imagedataTemplate.tpl
include indexTemplate.tpl

copy assets\